apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jobban-tls
  namespace: jobban
spec:
  secretName: jobban-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - jobban.inevitable.fyi
