apiVersion: v1
kind: Secret
metadata:
    name: jobban-app-secrets
    namespace: jobban
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:5ySqU7Fi4CTCWOV3436D6jghw3g6oSGmDV4EYJlx3q1U7Rg+DqjOkrFiToHki7HgkDTz43bQZLJrmu5DKx6yMg==,iv:T3bayLsbeJyTbkYrk9bp3okD/tvXT/OVXN3fEqHK4lc=,tag:Az6PGkMEZs1g11G8fATFEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVnFsNHNPU1hJbDFWUnBm
            c2hVTmprc2s0UHJjdjJCZXNibG1WVFBZNW5BClA0Y1o5TzJFdk9TMmZDZVNUU3Fp
            NnllL2JyTmhGSEFFRGxrMkFOL0tzb3cKLS0tIHV1cWo5TnNBYUVUSkZvWVUweG5W
            OTQ2Y3NXNTk0ZTMvUlhnN3o4T3lUc00K8JEoqGjKjbTuvr9DfPt8Tfqp1eqvx1nU
            f4X4b3kSVzffpy3E2viH6Ko8bjQwM3GVaH+qCP0IoL7ZCssHJ2XMFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gqdqq7uagezyew5uvhylgcasuntmltqx3mdxmwa6es5k393hg3ns4fsyrt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T12:10:39Z"
    mac: ENC[AES256_GCM,data:emGTJ7bPX5KZ1gm+RMNwC9K2a/YGDk58Itlf18trggnQ066xNJoXI7wGxkx6Ndzsw5mCVpwrYfEJCmWX06yIubMm2N9NnAioqThhA6smQzTg4KKotfuFBdV4LfystuFQC/hbTlK43yspwmyef786eVPO34nuSf9aDmQ1Rya8lK8=,iv:QYVnZcC6rD9f73HGEMpzQywkzZ1jkBVWQNtmsHjcbt0=,tag:LCfXtgxYAKkFb7TIzwS5kQ==,type:str]
    version: 3.13.0
