defmodule Jobban.Board.JobBrief do
  use Ecto.Schema
  import Ecto.Changeset

  @moduledoc """
  A per-listing briefing generated by `Jobban.Briefing`: what the company does
  (`company_overview`), where this role likely sits and what it does
  (`role_in_company`), and why that role matters to the company
  (`strategic_value`). One per job; regenerated, not edited.
  """

  schema "job_briefs" do
    field :company_overview, :string
    field :role_in_company, :string
    field :strategic_value, :string
    field :generated_at, :utc_datetime

    belongs_to :job, Jobban.Board.Job

    timestamps(type: :utc_datetime)
  end

  def changeset(brief, attrs) do
    brief
    |> cast(attrs, [:company_overview, :role_in_company, :strategic_value, :generated_at, :job_id])
    |> validate_required([:job_id])
    |> foreign_key_constraint(:job_id)
    |> unique_constraint(:job_id)
  end
end
