defmodule Jobban.Board.NetworkingTarget do
  use Ecto.Schema
  import Ecto.Changeset

  @moduledoc """
  One person-type to reach for a listing's networking play, generated by
  `Jobban.Networking`: who they are (`label`), the likely title for this role
  (`title_hint`), why they matter (`why`), `searches` — ready-to-run queries to
  actually find them (each `%{"query", "platform"}`, rendered as one-click
  pre-filled LinkedIn/Google searches), `how_to_find` (how to infer who they
  are), and the goal/`referral_path` — what to get from them and how to turn the
  contact into a referral. Read-only LLM guidance.
  """

  schema "networking_targets" do
    field :label, :string
    field :title_hint, :string
    field :why, :string
    field :searches, {:array, :map}, default: []
    field :how_to_find, :string
    field :referral_path, :string
    field :position, :integer, default: 0

    belongs_to :job, Jobban.Board.Job

    timestamps(type: :utc_datetime)
  end

  def changeset(target, attrs) do
    target
    |> cast(attrs, [
      :label,
      :title_hint,
      :why,
      :searches,
      :how_to_find,
      :referral_path,
      :position,
      :job_id
    ])
    |> validate_required([:label, :job_id])
    |> foreign_key_constraint(:job_id)
  end
end
